// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Zc-PRNJ1gf2BNjXO_AKOMgLX8tncZ5A',
    appId: '1:523023286132:web:db070f8285e0d12c21f621',
    messagingSenderId: '523023286132',
    projectId: 'docs-clone-flutter-fefc2',
    authDomain: 'docs-clone-flutter-fefc2.firebaseapp.com',
    storageBucket: 'docs-clone-flutter-fefc2.appspot.com',
    measurementId: 'G-XPX2Y82KV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBu2JmjxLW5DOYmYu9LOCjR7prTZ7gMAA',
    appId: '1:523023286132:android:4a2e28547b5d751721f621',
    messagingSenderId: '523023286132',
    projectId: 'docs-clone-flutter-fefc2',
    storageBucket: 'docs-clone-flutter-fefc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXSUZtTebKdUHuQzCjAIrY6-1dTLBRwQQ',
    appId: '1:523023286132:ios:b4d981a8788932fb21f621',
    messagingSenderId: '523023286132',
    projectId: 'docs-clone-flutter-fefc2',
    storageBucket: 'docs-clone-flutter-fefc2.appspot.com',
    iosClientId: '523023286132-hdiqtksue4ljdov9iapmovmarl42okbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.docsCloneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXSUZtTebKdUHuQzCjAIrY6-1dTLBRwQQ',
    appId: '1:523023286132:ios:b4d981a8788932fb21f621',
    messagingSenderId: '523023286132',
    projectId: 'docs-clone-flutter-fefc2',
    storageBucket: 'docs-clone-flutter-fefc2.appspot.com',
    iosClientId: '523023286132-hdiqtksue4ljdov9iapmovmarl42okbu.apps.googleusercontent.com',
    iosBundleId: 'com.example.docsCloneFlutter',
  );
}
